name: Build & Push (Docker Hub)

on:
  push:
    branches: [ main ]        # change if your default branch is different
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile               # update if your Dockerfile path is different
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sales:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sales:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales:buildcache,mode=max
